"use client";

import rough from "roughjs";
import { motion } from "framer-motion";
import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { usePrefersReducedMotion } from "@/hooks/useMediaQuery";

/** Breathing room between the child and the drawn ring. */
const PAD = 13;
/** Two passes with different seeds read as one scribble, not one clean oval. */
const SEEDS = [1337, 8021];

type SharpieProps = {
  children: ReactNode;
  className?: string;
  /** Always show the ring rather than only on hover or focus. */
  always?: boolean;
};

/**
 * Circles its child in International Orange, as if someone went over it with a
 * marker.
 *
 * The ring is generated by Rough.js from fixed seeds, so it is stable across
 * renders — a new scribble on every mouse-over would read as noise. It is
 * purely decorative: the child keeps its own focus ring and hit area.
 */
export function Sharpie({ children, className, always = false }: SharpieProps) {
  const ref = useRef<HTMLSpanElement>(null);
  const [box, setBox] = useState<{ w: number; h: number } | null>(null);
  const [lit, setLit] = useState(false);
  const reduced = usePrefersReducedMotion();

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const measure = () => {
      const rect = el.getBoundingClientRect();
      setBox({ w: Math.round(rect.width), h: Math.round(rect.height) });
    };
    measure();
    const observer = new ResizeObserver(measure);
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  const rings = useMemo(() => {
    if (!box || box.w === 0) return [];
    const width = box.w + PAD * 2;
    const height = box.h + PAD * 2;
    const generator = rough.generator();

    return SEEDS.flatMap((seed, index) =>
      generator
        .toPaths(
          generator.ellipse(width / 2, height / 2, width - 3 - index * 5, height - 4 - index * 4, {
            roughness: 2.3,
            bowing: 1.7,
            stroke: "#0b5fd0",
            strokeWidth: 2.6,
            seed,
          }),
        )
        .map((path, i) => ({ ...path, key: `${seed}-${i}` })),
    );
  }, [box]);

  const show = always || lit;

  return (
    <span
      ref={ref}
      className={`relative inline-flex ${className ?? ""}`}
      onPointerEnter={() => setLit(true)}
      onPointerLeave={() => setLit(false)}
      onFocus={() => setLit(true)}
      onBlur={() => setLit(false)}
    >
      {children}

      {box && rings.length > 0 ? (
        <svg
          aria-hidden="true"
          className="pointer-events-none absolute overflow-visible"
          style={{ left: -PAD, top: -PAD, width: box.w + PAD * 2, height: box.h + PAD * 2 }}
          viewBox={`0 0 ${box.w + PAD * 2} ${box.h + PAD * 2}`}
          fill="none"
        >
          {rings.map((ring, index) => (
            <motion.path
              key={ring.key}
              d={ring.d}
              stroke={ring.stroke}
              strokeWidth={ring.strokeWidth}
              strokeLinecap="round"
              initial={false}
              animate={{ pathLength: show ? 1 : 0, opacity: show ? 1 : 0 }}
              transition={
                reduced
                  ? { duration: 0 }
                  : { duration: 0.34, delay: show ? index * 0.06 : 0, ease: [0.22, 0.68, 0, 1] }
              }
            />
          ))}
        </svg>
      ) : null}
    </span>
  );
}
